[theme]
base = "dark"

# General color setup
primaryColor="#5ea8ff"
backgroundColor="#EFEDED"
secondaryBackgroundColor="#0d7bec"
textColor="#000000"

# Widgets
showWidgetBorder = true
borderColor = "#314158"

# Dataframes
dataframeHeaderBackgroundColor = "#1d293d"

# Base text
font = "Josefin Sans"
baseFontWeight = 300
baseFontSize = 14

# Heading text
headingFont = "Josefin Sans"
headingFontWeights = [300, 400, 400, 300, 300, 300]
headingFontSizes = ["2.5rem", "1.5rem", "1rem"]

[[theme.fontFaces]]
family = "Josefin Sans"
style = "normal"
weight = "300 700"
url = "https://fonts.gstatic.com/s/josefinsans/v33/Qw3aZQNVED7rKGKxtqIqX5EUDX5n8A.woff2"
