[theme]
base = "dark"

primaryColor="#7b7050"
backgroundColor="#50505a"
secondaryBackgroundColor="#3a3a48"
textColor="#e2e8f0"

showWidgetBorder = true
borderColor = "#314158"
dataframeHeaderBackgroundColor = "#1d293d"

font = "Comfortaa"
baseFontWeight = 400
baseFontSize = 14

headingFont = "Comfortaa"
headingFontWeights = [300, 400, 700]
headingFontSizes = ["2.5rem", "1.5rem", "1rem"]

[[theme.fontFaces]]
family = "Comfortaa"
style = "normal"
weight = "300"
url = "https://fonts.gstatic.com/s/comfortaa/v29/1Ptgg87LROyAm0K08i4C9eu0.woff2"

[[theme.fontFaces]]
family = "Comfortaa"
style = "normal"
weight = "400"
url = "https://fonts.gstatic.com/s/comfortaa/v29/1Ptsg87LROyAm0K08i4C.woff2"

[[theme.fontFaces]]
family = "Comfortaa"
style = "normal"
weight = "700"
url = "https://fonts.gstatic.com/s/comfortaa/v29/1Ptvg87LROyAm0K08i4C9cS9.woff2"
